# Generated by Django 3.2.14 on 2023-07-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
